services:

  # =========================================================
  # BACKEND - Spring Boot
  # =========================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: nguongocso-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8080:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  # =========================================================
  # FRONTEND - React / Vite / Nginx
  # =========================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: nguongocso-frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend